#Run this code from whatever folder
#you want the data to be in.
from __future__ import unicode_literals
import youtube_dl


ydl_opts = {
    'format': 'bestaudio/best',
    'postprocessors': [{
        'key': 'FFmpegExtractAudio',
        'preferredcodec': 'mp3',
        'preferredquality': '192',
    }],
}
with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    #ydl.download(['https://www.youtube.com/watch?v=La4Dcd1aUcE'])
    #ydl.download(['https://www.youtube.com/watch?v=Kvgz6swo-vY'])
    #ydl.download(['https://www.youtube.com/watch?v=FTQbiNvZqaY'])
    ydl.download(['https://www.youtube.com/watch?v=Q86nf7mpOXk)'])
    ydl.download(['https://www.youtube.com/watch?v=LHCob76kigA'])
    ydl.download(['https://www.youtube.com/watch?v=djV11Xbc914'])
    ydl.download(['https://www.youtube.com/watch?v=DC8FsIdVi9Y'])
    ydl.download(['https://www.youtube.com/watch?v=Vnoz5uBEWOA'])
    ydl.download(['https://www.youtube.com/watch?v=n4RjJKxsamQ'])
    ydl.download(['https://www.youtube.com/watch?v=FjRPDzcmJT4'])
    ydl.download(['https://www.youtube.com/watch?v=kn6-c223DUU'])
    ydl.download(['https://www.youtube.com/watch?v=6I2y_UbVz4U'])
    ydl.download(['https://www.youtube.com/watch?v=9vMh9f41pqE'])
    ydl.download(['https://www.youtube.com/watch?v=5anLPw0Efmo'])
    ydl.download(['https://www.youtube.com/watch?v=1TsVjvEkc4s'])
    ydl.download(['https://www.youtube.com/watch?v=vNoKguSdy4Y'])
    ydl.download(['https://www.youtube.com/watch?v=XjwZAa2EjKA'])
    ydl.download(['https://www.youtube.com/watch?v=Y7ix6RITXM0'])
    ydl.download(['https://www.youtube.com/watch?v=D7K3wFXJFsQ'])
    ydl.download(['https://www.youtube.com/watch?v=fk4BbF7B29w'])
    ydl.download(['https://www.youtube.com/watch?v=zRIbf6JqkNc'])
    ydl.download(['https://www.youtube.com/watch?v=VBmMU_iwe6U'])
    ydl.download(['https://www.youtube.com/watch?v=ZyhrYis509A'])
    ydl.download(['https://www.youtube.com/watch?v=PIb6AZdTr-A'])
    ydl.download(['https://www.youtube.com/watch?v=36mCEZzzQ3o'])
    ydl.download(['https://www.youtube.com/watch?v=DzwkcbTQ7ZE'])
    ydl.download(['https://www.youtube.com/watch?v=KrVC5dm5fFc'])
    ydl.download(['https://www.youtube.com/watch?v=bg1sT4ILG0w'])
    ydl.download(['https://www.youtube.com/watch?v=weRHyjj34ZE'])
    ydl.download(['https://www.youtube.com/watch?v=fJ9rUzIMcZQ'])
    ydl.download(['https://www.youtube.com/watch?v=yd8jh9QYfEs'])
    ydl.download(['https://www.youtube.com/watch?v=iP6XpLQM2Cs'])
    ydl.download(['https://www.youtube.com/watch?v=9WbCfHutDSE'])
    ydl.download(['https://www.youtube.com/watch?v=3YxaaGgTQYM'])
    ydl.download(['https://www.youtube.com/watch?v=TR3Vdo5etCQ'])
    ydl.download(['https://www.youtube.com/watch?v=qDRORgoZxZU'])
    ydl.download(['https://www.youtube.com/watch?v=gdx7gN1UyX0'])
    ydl.download(['https://www.youtube.com/watch?v=YnwsMEabmSo'])
    ydl.download(['https://www.youtube.com/watch?v=rClUOdS5Zyw'])
    ydl.download(['https://www.youtube.com/watch?v=nPvuNsRccVw'])
    ydl.download(['https://www.youtube.com/watch?v=cmSbXsFE3l8'])
    ydl.download(['https://www.youtube.com/watch?v=HHP5MKgK0o8'])
    ydl.download(['https://www.youtube.com/watch?v=-2U0Ivkn2Ds'])
    ydl.download(['https://www.youtube.com/watch?v=8WYHDfJDPDc'])
    ydl.download(['https://www.youtube.com/watch?v=Wa5B22KAkEk'])
    ydl.download(['https://www.youtube.com/watch?v=ShlW5plD_40'])
    ydl.download(['https://www.youtube.com/watch?v=vxc1ufJxPGM'])
    ydl.download(['https://www.youtube.com/watch?v=SAXpBgkXt60'])
    ydl.download(['https://www.youtube.com/watch?v=Ri7-vnrJD3k'])
    ydl.download(['https://www.youtube.com/watch?v=9BMwcO6_hyA'])
    ydl.download(['https://www.youtube.com/watch?v=aCeHAVMbVqM'])
    ydl.download(['https://www.youtube.com/watch?v=RubBzkZzpUA'])
    ydl.download(['https://www.youtube.com/watch?v=YlUKcNNmywk'])
    ydl.download(['https://www.youtube.com/watch?v=EkHTsc9PU2A'])
    ydl.download(['https://www.youtube.com/watch?v=lgT1AidzRWM'])
    ydl.download(['https://www.youtube.com/watch?v=Ho32Oh6b4jc'])
    ydl.download(['https://www.youtube.com/watch?v=SRcnnId15BA'])
    ydl.download(['https://www.youtube.com/watch?v=O6xyD4CY_Sg'])
    ydl.download(['https://www.youtube.com/watch?v=Q_mQxKviRJM'])
    ydl.download(['https://www.youtube.com/watch?v=GTyN-DB_v5M'])
    ydl.download(['https://www.youtube.com/watch?v=nSDgHBxUbVQ'])
    ydl.download(['https://www.youtube.com/watch?v=Bag1gUxuU0g'])
    ydl.download(['https://www.youtube.com/watch?v=47dtFZ8CFo8'])
    ydl.download(['https://www.youtube.com/watch?v=lDK9QqIzhwk'])
    ydl.download(['https://www.youtube.com/watch?v=CvBfHwUxHIk'])
    ydl.download(['https://www.youtube.com/watch?v=xwtdhWltSIg'])
    ydl.download(['https://www.youtube.com/watch?v=vJwKKKd2ZYE'])
    ydl.download(['https://www.youtube.com/watch?v=QNJL6nfu__Q'])
    ydl.download(['https://www.youtube.com/watch?v=ZaI2IlHwmgQ'])
    ydl.download(['https://www.youtube.com/watch?v=vbPC_81gGs4'])
    ydl.download(['https://www.youtube.com/watch?v=_kqQDCxRCzM'])
    ydl.download(['https://www.youtube.com/watch?v=bvC_0foemLY'])
    ydl.download(['https://www.youtube.com/watch?v=b-J95fYuVz4'])
    ydl.download(['https://www.youtube.com/watch?v=WLTI2rWAlV4'])
    ydl.download(['https://www.youtube.com/watch?v=RgKAFK5djSk'])
    ydl.download(['https://www.youtube.com/watch?v=fRh_vgS2dFE'])
    ydl.download(['https://www.youtube.com/watch?v=OPf0YbXqDm0'])
    ydl.download(['https://www.youtube.com/watch?v=e-ORhEE9VVg'])
    ydl.download(['https://www.youtube.com/watch?v=nfWlot6h_JM'])
    ydl.download(['https://www.youtube.com/watch?v=YqeW9_5kURI'])
    ydl.download(['https://www.youtube.com/watch?v=YQHsXMglC9A'])
    ydl.download(['https://www.youtube.com/watch?v=CevxZvSJLk8'])
    ydl.download(['https://www.youtube.com/watch?v=09R8_2nJtjg'])
    ydl.download(['https://www.youtube.com/watch?v=7PCkvCPvDXk'])
    ydl.download(['https://www.youtube.com/watch?v=2vjPBrBU-TM'])
    ydl.download(['https://www.youtube.com/watch?v=DK_0jXPuIr0'])
    ydl.download(['https://www.youtube.com/watch?v=lp-EO5I60KA'])
    ydl.download(['https://www.youtube.com/watch?v=5GL9JoH4Sws'])
    ydl.download(['https://www.youtube.com/watch?v=AJtDXIazrMo'])
    ydl.download(['https://www.youtube.com/watch?v=kOkQ4T5WO9E'])
    ydl.download(['https://www.youtube.com/watch?v=RBumgq5yVrA'])
    ydl.download(['https://www.youtube.com/watch?v=pRpeEdMmmQ0'])
    ydl.download(['https://www.youtube.com/watch?v=YBHQbu5rbdQ'])
    ydl.download(['https://www.youtube.com/watch?v=uelHwf8o7_U'])
    ydl.download(['https://www.youtube.com/watch?v=PT2_F-1esPk'])
    ydl.download(['https://www.youtube.com/watch?v=KQ6zr6kCPj8'])
    ydl.download(['https://www.youtube.com/watch?v=IcrbM1l_BoI'])
    ydl.download(['https://www.youtube.com/watch?v=vjW8wmF5VWc)'])
    ydl.download(['https://www.youtube.com/watch?v=PIh2xe4jnpk'])
    ydl.download(['https://www.youtube.com/watch?v=uxpDa-c-4Mc&list=PLlqfMtrmorvl1TU5fqoIukJ64THrqcIKK&index=6&t=0s'])
    ydl.download(['https://www.youtube.com/watch?v=oyEuk8j8imI'])
    ydl.download(['https://www.youtube.com/watch?v=xscJ8Lla6Gc'])
    ydl.download(['https://www.youtube.com/watch?v=rYEDA3JcQqw'])
