#Run this code from whatever folder
#you want the data to be in.
from __future__ import unicode_literals
import youtube_dl


ydl_opts = {
    'format': 'bestaudio/best',
    'postprocessors': [{
        'key': 'FFmpegExtractAudio',
        'preferredcodec': 'wav',
        'preferredquality': '192',
    }],
}
with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    ydl.download(['https://www.youtube.com/watch?v=sQnlR2effdQ'])
    ydl.download(['https://www.youtube.com/watch?v=oiKj0Z_Xnjc'])
    ydl.download(['https://www.youtube.com/watch?v=mF5etHMRMMM'])
    ydl.download(['https://www.youtube.com/watch?v=8Si2q_rxvWA'])
    ydl.download(['https://www.youtube.com/watch?v=wjud3Ue-pFE&list=PLG1Isko37I2xS2bD9DYgmEtHiqmQCtTSU&index=2'])
    ydl.download(['https://www.youtube.com/watch?v=K5KAc5CoCuk'])
    ydl.download(['https://www.youtube.com/watch?v=FomT_qar0GE'])
    ydl.download(['https://www.youtube.com/watch?v=Y7-vP7TnluY'])
    ydl.download(['https://www.youtube.com/watch?v=BvIvwHoG5fs'])
    ydl.download(['https://www.youtube.com/watch?v=NiHWwKC8WjU'])
    ydl.download(['https://www.youtube.com/watch?v=VHoT4N43jK8'])
    ydl.download(['https://www.youtube.com/watch?v=cwaAppsy5yo'])
    ydl.download(['https://www.youtube.com/watch?v=NwVA5zYfNWw'])
    ydl.download(['https://www.youtube.com/watch?v=cmE_aahc448'])
    ydl.download(['https://www.youtube.com/watch?v=4J39Ol6T0Xw'])
    ydl.download(['https://www.youtube.com/watch?v=U-Z_bZS8t3M'])
    ydl.download(['https://www.youtube.com/watch?v=i0p5aZBvAoo'])
    ydl.download(['https://www.youtube.com/watch?v=bPxwu5OZ-HM'])
    ydl.download(['https://www.youtube.com/watch?v=63K5VMx2BZM'])
    ydl.download(['https://www.youtube.com/watch?v=f6GHAbenqvM'])
    ydl.download(['https://www.youtube.com/watch?v=lcSakE8U6lk'])
    ydl.download(['https://www.youtube.com/watch?v=mOuzyjsGYXc'])
    ydl.download(['https://www.youtube.com/watch?v=519_pOvP9xs'])
    ydl.download(['https://www.youtube.com/watch?v=vCRThAYKXEc'])
    ydl.download(['https://www.youtube.com/watch?v=7l2o1tgFZGk'])
    ydl.download(['https://www.youtube.com/watch?v=H7rhMqTQ4WI'])
    ydl.download(['https://www.youtube.com/watch?v=VcViDBhgJrM'])
    ydl.download(['https://www.youtube.com/watch?v=hoPIDJy93Nc'])
    ydl.download(['https://www.youtube.com/watch?v=uDyHQGHic0I'])
    ydl.download(['https://www.youtube.com/watch?v=13o1i-cgTOA'])
    ydl.download(['https://www.youtube.com/watch?v=O8Lv32YyAgU'])
    ydl.download(['https://www.youtube.com/watch?v=O8MClBoNlfE'])
    ydl.download(['https://www.youtube.com/watch?v=egwvEm3nbmc'])
    ydl.download(['https://www.youtube.com/watch?v=EC7Re8cczj0'])
    ydl.download(['https://www.youtube.com/watch?v=jyBN6lbhUFM'])
    ydl.download(['https://www.youtube.com/watch?v=aS1SGkWoHec'])
    ydl.download(['https://www.youtube.com/watch?v=2zdqymnZoHc'])
    ydl.download(['https://www.youtube.com/watch?v=hmF_AasWf2g'])
    ydl.download(['https://www.youtube.com/watch?v=AW5zbbXbaN4'])
    ydl.download(['https://www.youtube.com/watch?v=tPXHhB8woyc'])
    ydl.download(['https://www.youtube.com/watch?v=tB-zasOL29Y'])
    ydl.download(['https://www.youtube.com/watch?v=zSpLOlxy9nI'])
    ydl.download(['https://www.youtube.com/watch?v=i3u0vq0WyIA'])
    ydl.download(['https://www.youtube.com/watch?v=uduL7z8BkOs'])
    ydl.download(['https://www.youtube.com/watch?v=TL-q_xCggTE'])
    ydl.download(['https://www.youtube.com/watch?v=V82wcQbfZmc'])
    ydl.download(['https://www.youtube.com/watch?v=pv-49f38H9M'])
    ydl.download(['https://www.youtube.com/watch?v=AfkiMp7piiY'])
    ydl.download(['https://www.youtube.com/watch?v=2wicVDVQzzM'])
    ydl.download(['https://www.youtube.com/watch?v=KAOmC5qT02w'])
    ydl.download(['https://www.youtube.com/watch?v=21NYo61E3M4'])
    ydl.download(['https://www.youtube.com/watch?v=2uktfm6uGAE'])
    ydl.download(['https://www.youtube.com/watch?v=N6dAfbR5kK4'])
    ydl.download(['https://www.youtube.com/watch?v=LuAQHcYDuYY'])
    ydl.download(['https://www.youtube.com/watch?v=p9_B9UABex0'])
    ydl.download(['https://www.youtube.com/watch?v=7Vv5sDQ9aFU'])
    ydl.download(['https://www.youtube.com/watch?v=6XHwKRnDZmk'])
    ydl.download(['https://www.youtube.com/watch?v=lgUHb-_t2_U'])
    ydl.download(['https://www.youtube.com/watch?v=PHWzFM_Hxvo&index=8&list=PLlCVFNj9AHx9j-x96D9_BwTm4H0avU1RG'])
    ydl.download(['https://www.youtube.com/watch?v=0EGrlRA9Ut8'])
    ydl.download(['https://www.youtube.com/watch?v=DDJoTizuUpM'])
    ydl.download(['https://www.youtube.com/watch?v=3Hr_gmFWfA4'])
    ydl.download(['https://www.youtube.com/watch?v=_0S3idlfO40'])
    ydl.download(['https://www.youtube.com/watch?v=Y99UqvgCmE8'])
    ydl.download(['https://www.youtube.com/watch?v=XzoirUEntug'])
    ydl.download(['https://www.youtube.com/watch?v=k77AMWp8t64'])
    ydl.download(['https://www.youtube.com/watch?v=YUIHo_V85Xc'])
    ydl.download(['https://www.youtube.com/watch?v=LZPT5_k5Al4'])
    ydl.download(['https://www.youtube.com/watch?v=ybW7B3IFRh4'])
    ydl.download(['https://www.youtube.com/watch?v=FsJWSDe44Uk'])
    ydl.download(['https://www.youtube.com/watch?v=1mvz7I7Dp5c'])
    ydl.download(['https://www.youtube.com/watch?v=1aPAcGKuZfA'])
    ydl.download(['https://www.youtube.com/watch?v=AS4GlgkW5Fc'])
    ydl.download(['https://www.youtube.com/watch?v=YAS8-_w9wQQ'])
    ydl.download(['https://www.youtube.com/watch?v=qhYtVMoWFNQ'])
    ydl.download(['https://www.youtube.com/watch?v=1VTtR1ftPJU'])
    ydl.download(['https://www.youtube.com/watch?v=ODAxvuGsYYY'])
    ydl.download(['https://www.youtube.com/watch?v=XVW5qA7QLmw'])
    ydl.download(['https://www.youtube.com/watch?v=EbrrSSvrSZ8'])
    ydl.download(['https://www.youtube.com/watch?v=pQtisw9837A'])
    ydl.download(['https://www.youtube.com/watch?v=2Zp3agWZmOg'])
    ydl.download(['https://www.youtube.com/watch?v=Pw3D0cVQiek'])
    ydl.download(['https://www.youtube.com/watch?v=Y4uOM7s38XA'])
    ydl.download(['https://www.youtube.com/watch?v=P5jVK5kD0y0'])
    ydl.download(['https://www.youtube.com/watch?v=N9oCFfRXEF4'])
    ydl.download(['https://www.youtube.com/watch?v=wtK6JClJXvg'])
    ydl.download(['https://www.youtube.com/watch?v=dE7oGkrIjvs'])
    ydl.download(['https://www.youtube.com/watch?v=GME3fMeK5ts'])
    ydl.download(['https://www.youtube.com/watch?v=W7RTg-dViKg'])
    ydl.download(['https://www.youtube.com/watch?v=M7X6oYg6iro&list=RD75MMjly5AjM&index=9&app=desktop'])
    ydl.download(['https://www.youtube.com/watch?v=2bAMyiaIwNk'])
    ydl.download(['https://www.youtube.com/watch?v=S0nnZEKC42U'])
    ydl.download(['https://www.youtube.com/watch?v=vLxavctn240'])
    ydl.download(['https://www.youtube.com/watch?v=FAI8zaw4h7o'])
    ydl.download(['https://www.youtube.com/watch?v=pdPwbUk4R34'])
    ydl.download(['https://www.youtube.com/watch?v=guADTFlEHJE'])
    ydl.download(['https://www.youtube.com/watch?v=OZfJf-8xwKM'])
    ydl.download(['https://www.youtube.com/watch?v=qhzZTcBBhaU'])
    ydl.download(['https://www.youtube.com/watch?v=hvi2uY2rgns'])
    ydl.download(['https://www.youtube.com/watch?v=Gsz7IuZ3paM'])
