#Run this code from whatever folder
#you want the data to be in.
from __future__ import unicode_literals
import youtube_dl


ydl_opts = {
    'format': 'bestaudio/best',
    'postprocessors': [{
        'key': 'FFmpegExtractAudio',
        'preferredcodec': 'wav',
        'preferredquality': '192',
    }],
}
with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    ydl.download(['https://www.youtube.com/watch?v=nDuE4ZGSzes'])
    ydl.download(['https://www.youtube.com/watch?v=sr--GVIoluU'])
    ydl.download(['https://www.youtube.com/watch?v=VF2nSitbit4'])
    ydl.download(['https://www.youtube.com/watch?v=6Ghs7yFA538'])
    ydl.download(['https://www.youtube.com/watch?v=ypRTzt1KrF8'])
    ydl.download(['https://www.youtube.com/watch?v=uE2vcBO8iqo'])
    ydl.download(['https://www.youtube.com/watch?v=furPeOfxPF8'])
    ydl.download(['https://www.youtube.com/watch?v=wQ_POfToaVY'])
    ydl.download(['https://www.youtube.com/watch?v=Spe4f7vPvCo'])
    ydl.download(['https://www.youtube.com/watch?v=7DwAwNNHaW8'])
    ydl.download(['https://www.youtube.com/watch?v=zoOiWFT0dVE'])
    ydl.download(['https://www.youtube.com/watch?v=uGIqvJcNZ1w'])
    ydl.download(['https://www.youtube.com/watch?v=7C2z4GqqS5E'])
    ydl.download(['https://www.youtube.com/watch?v=DP_AY52YsMg'])
    ydl.download(['https://www.youtube.com/watch?v=Dx_fKPBPYUI'])
    ydl.download(['https://www.youtube.com/watch?v=RlUb2F-zLxw'])
    ydl.download(['https://www.youtube.com/watch?v=DdLYSziSXII'])
    ydl.download(['https://www.youtube.com/watch?v=ePpPVE-GGJw'])
    ydl.download(['https://www.youtube.com/watch?v=Uh6dkL1M9DM'])
    ydl.download(['https://www.youtube.com/watch?v=PFcDGxeuTUk'])
    ydl.download(['https://www.youtube.com/watch?v=7WTvGZqinR8'])
    ydl.download(['https://www.youtube.com/watch?v=wMpv4T1r92g'])
    ydl.download(['https://www.youtube.com/watch?v=MBdVXkSdhwU'])
    ydl.download(['https://www.youtube.com/watch?v=k_YdEflTv9s'])
    ydl.download(['https://www.youtube.com/watch?v=IX87le_EokM'])
    ydl.download(['https://www.youtube.com/watch?v=kTlv5_Bs8aw'])
    ydl.download(['https://www.youtube.com/watch?v=i0p1bmr0EmE'])
    ydl.download(['https://www.youtube.com/watch?v=V2hlQkVJZhE'])
    ydl.download(['https://www.youtube.com/watch?v=aCxGqtDoB04'])
    ydl.download(['https://www.youtube.com/watch?v=4klxELBjbRw'])
    ydl.download(['https://www.youtube.com/watch?v=IjFaR-qPr0M'])
    ydl.download(['https://www.youtube.com/watch?v=AueFEnoXBK8'])
    ydl.download(['https://www.youtube.com/watch?v=8BvkFjqz98Y'])
    ydl.download(['https://www.youtube.com/watch?v=2MNL2mU8pBE'])
    ydl.download(['https://www.youtube.com/watch?v=DnrgxgB464U'])
    ydl.download(['https://www.youtube.com/watch?v=GR7B4aJgAjI'])
    ydl.download(['https://www.youtube.com/watch?v=7EIPPktOcVQ'])
    ydl.download(['https://www.youtube.com/watch?v=zCLJtnj07SU'])
    ydl.download(['https://www.youtube.com/watch?v=rRzxEiBLQCA'])
    ydl.download(['https://www.youtube.com/watch?v=GWkzOHDcqGg'])
    ydl.download(['https://www.youtube.com/watch?v=ViN6dPU-NJI'])
    ydl.download(['https://www.youtube.com/watch?v=_rXAwNw1Dfw'])
    ydl.download(['https://www.youtube.com/watch?v=A37bu5BFaWs'])
    ydl.download(['https://www.youtube.com/watch?v=jhOVibLEDhA'])
    ydl.download(['https://www.youtube.com/watch?v=uDaKPPmDSIE'])
    ydl.download(['https://www.youtube.com/watch?v=Xse95BGhVXo'])
    ydl.download(['https://www.youtube.com/watch?v=XqWQ9fQnxKo'])
    ydl.download(['https://www.youtube.com/watch?v=3A8ReZ_punE'])
    ydl.download(['https://www.youtube.com/watch?v=9_KJ_HbY6Mw'])
    ydl.download(['https://www.youtube.com/watch?v=E13jVMczRJg'])
    ydl.download(['https://www.youtube.com/watch?v=RIvXxQTuQ18'])
    ydl.download(['https://www.youtube.com/watch?v=chuW-EhWgGI'])
    ydl.download(['https://www.youtube.com/watch?v=LaNmyiHMgXw'])
    ydl.download(['https://www.youtube.com/watch?v=t45h-8Ln2Gc'])
    ydl.download(['https://www.youtube.com/watch?v=IHNzOHi8sJs'])
    ydl.download(['https://www.youtube.com/watch?v=CpdmskJ0arM'])
    ydl.download(['https://www.youtube.com/watch?v=wLSBXJiyK9U'])
    ydl.download(['https://www.youtube.com/watch?v=Q_N47K6Qiao'])
    ydl.download(['https://www.youtube.com/watch?v=JQGRg8XBnB4'])
    ydl.download(['https://www.youtube.com/watch?v=q48m_KOetJs'])
    ydl.download(['https://www.youtube.com/watch?v=e9ddYTUuFuo'])
    ydl.download(['https://www.youtube.com/watch?v=E1fbxVIckHg'])
    ydl.download(['https://www.youtube.com/watch?v=zhCtzmDWsN0'])
    ydl.download(['https://www.youtube.com/watch?v=jKVxngiwMq8'])
    ydl.download(['https://www.youtube.com/watch?v=iyemskFPrtc'])
    ydl.download(['https://www.youtube.com/watch?v=q3W0BNnqIlQ'])
    ydl.download(['https://www.youtube.com/watch?v=h52EITY0YoU'])
    ydl.download(['https://www.youtube.com/watch?v=AoJqnAoBHsk'])
    ydl.download(['https://www.youtube.com/watch?v=rS0sZbtQ3Ek'])
    ydl.download(['https://www.youtube.com/watch?v=9BMKJLdb3eY'])
    ydl.download(['https://www.youtube.com/watch?v=qcPSTq3x9UU'])
    ydl.download(['https://www.youtube.com/watch?v=cOgElxBwCO4'])
    ydl.download(['https://www.youtube.com/watch?v=MslES96hLeo'])
    ydl.download(['https://www.youtube.com/watch?v=hd2GO1ykb2o'])
    ydl.download(['https://www.youtube.com/watch?v=zA4yZeRQqNc'])
    ydl.download(['https://www.youtube.com/watch?v=DFL3XhVeG_o'])
    ydl.download(['https://www.youtube.com/watch?v=VUfMsIB6sJE'])
    ydl.download(['https://www.youtube.com/watch?v=3RJeJ8Luwnw'])
    ydl.download(['https://www.youtube.com/watch?v=zm1hWwBks7I'])
    ydl.download(['https://www.youtube.com/watch?v=V0U10XTx2Mg'])
    ydl.download(['https://www.youtube.com/watch?v=lc_-atsKtxM'])
    ydl.download(['https://www.youtube.com/watch?v=HuoOEry-Yc4'])
    ydl.download(['https://www.youtube.com/watch?v=eaJHiX8z8Og'])
    ydl.download(['https://www.youtube.com/watch?v=Fm5iP0S1z9w'])
    ydl.download(['https://www.youtube.com/watch?v=GvlpXh11oe0'])
    ydl.download(['https://www.youtube.com/watch?v=kuaaJX9lsqY'])
    ydl.download(['https://www.youtube.com/watch?v=qyQvbemmlN8'])
    ydl.download(['https://www.youtube.com/watch?v=m-47M_raW2s'])
    ydl.download(['https://www.youtube.com/watch?v=9VIU3zZXZvs'])
    ydl.download(['https://www.youtube.com/watch?v=6leBPLEkpEk'])
    ydl.download(['https://www.youtube.com/watch?v=XtDKg4Woiwc'])
    ydl.download(['https://www.youtube.com/watch?v=ywnV50q7S78'])
