#Run this code from whatever folder
#you want the data to be in.
from __future__ import unicode_literals
import youtube_dl

ydl_opts = {
    'format': 'bestaudio/best',
    'postprocessors': [{
        'key': 'FFmpegExtractAudio',
        'preferredcodec': 'wav',
        'preferredquality': '192',
    }],
}
with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    ydl.download(['https://www.youtube.com/watch?v=Ahwc-ouFeTQ'])
    ydl.download(['https://www.youtube.com/watch?v=nyrcAPJSRJc'])
    ydl.download(['https://www.youtube.com/watch?v=uT-hBZXTwEI'])
    ydl.download(['https://www.youtube.com/watch?v=5kmEM2u1dZA'])
    ydl.download(['https://www.youtube.com/watch?v=82NBsCOQoi4'])
    ydl.download(['https://www.youtube.com/watch?v=2CGv2Ud-KoE'])
    ydl.download(['https://www.youtube.com/watch?v=l1FFp_4C--I'])
    ydl.download(['https://www.youtube.com/watch?v=O9V1ekvSAhg'])
    ydl.download(['https://www.youtube.com/watch?v=AMT9IOyXmBM'])
    ydl.download(['https://www.youtube.com/watch?v=YaKG5cUVB30'])
    ydl.download(['https://www.youtube.com/watch?v=VeYfi8O0OOQ'])
    ydl.download(['https://www.youtube.com/watch?v=drFsXLChrWc'])
    ydl.download(['https://www.youtube.com/watch?v=HbtGDZf9Ts8'])
    ydl.download(['https://www.youtube.com/watch?v=vGrfFzagzHs'])
    ydl.download(['https://www.youtube.com/watch?v=EEdyjP34CsY'])
    ydl.download(['https://www.youtube.com/watch?v=7_tWN9Iei7Y'])
    ydl.download(['https://www.youtube.com/watch?v=j1z_gb7ngLQ'])
    ydl.download(['https://www.youtube.com/watch?v=fvkacsZFJE0'])
    ydl.download(['https://www.youtube.com/watch?v=kiMG_JV2gbo'])
    ydl.download(['https://www.youtube.com/watch?v=lQ03Lo-hLmI'])
    ydl.download(['https://www.youtube.com/watch?v=Cf27Q2bfftQ'])
    ydl.download(['https://www.youtube.com/watch?v=qYRCiQ6d35w'])
    ydl.download(['https://www.youtube.com/watch?v=ysAEZOwp5rM'])
    ydl.download(['https://www.youtube.com/watch?v=5a0xis7mONc'])
    ydl.download(['https://www.youtube.com/watch?v=RveIJFR7LV4'])
    ydl.download(['https://www.youtube.com/watch?v=GSV1PBthpgQ'])
    ydl.download(['https://www.youtube.com/watch?v=yqObMM_QzVQ'])
    ydl.download(['https://www.youtube.com/watch?v=fkMg_X9lHMc'])
    ydl.download(['https://www.youtube.com/watch?v=O3UBOOZw-FE'])
    ydl.download(['https://www.youtube.com/watch?v=40ouL7n1sQk'])
    ydl.download(['https://www.youtube.com/watch?v=1il3RFk5Okw'])
    ydl.download(['https://www.youtube.com/watch?v=cZ58odQo87A'])
    ydl.download(['https://www.youtube.com/watch?v=5PST7Ld4wWU'])
    ydl.download(['https://www.youtube.com/watch?v=MU7jt2-LHAc'])
    ydl.download(['https://www.youtube.com/watch?v=TxnJoF9qmkA'])
    ydl.download(['https://www.youtube.com/watch?v=b3cU182bGfQ'])
    ydl.download(['https://www.youtube.com/watch?v=V9Y-BM-I_x0'])
    ydl.download(['https://www.youtube.com/watch?v=vmj2Ab1GknA'])
    ydl.download(['https://www.youtube.com/watch?v=o337Ne80ePU'])
    ydl.download(['https://www.youtube.com/watch?v=QRs33vbhyvA'])
    ydl.download(['https://www.youtube.com/watch?v=YGpak_xS47o'])
    ydl.download(['https://www.youtube.com/watch?v=-uZvLNIQMKQ'])
    ydl.download(['https://www.youtube.com/watch?v=pLHnnJRaP7Q'])
    ydl.download(['https://www.youtube.com/watch?v=4tDpYxNYqPg'])
    ydl.download(['https://www.youtube.com/watch?v=4iXXTgOvBAc'])
    ydl.download(['https://www.youtube.com/watch?v=gx9KFXb5x_o'])
    ydl.download(['https://www.youtube.com/watch?v=vAI7PMkt2Bc'])
    ydl.download(['https://www.youtube.com/watch?v=2Ra5czl1Tgc'])
    ydl.download(['https://www.youtube.com/watch?v=Vk0wDlG838E'])
    ydl.download(['https://www.youtube.com/watch?v=8HWUQW49wBk'])
    ydl.download(['https://www.youtube.com/watch?v=1EMFt7m_8yE'])
    ydl.download(['https://www.youtube.com/watch?v=RsZvjqG2lec'])
    ydl.download(['https://www.youtube.com/watch?v=C9HL-2IhZKg'])
    ydl.download(['https://www.youtube.com/watch?v=kDMFranvFuQ'])
    ydl.download(['https://www.youtube.com/watch?v=oq0rrYrufYU'])
    ydl.download(['https://www.youtube.com/watch?v=DraA3PUuoQc'])
    ydl.download(['https://www.youtube.com/watch?v=FPvVZG9hlVY'])
    ydl.download(['https://www.youtube.com/watch?v=ZbsqG_R3ySE'])
    ydl.download(['https://www.youtube.com/watch?v=B6ApzrQXEss'])
    ydl.download(['https://www.youtube.com/watch?v=NRbD3ggyc7U'])
    ydl.download(['https://www.youtube.com/watch?v=xFnlPF3KUqo'])
    ydl.download(['https://www.youtube.com/watch?v=RVTvrzjQAGY'])
    ydl.download(['https://www.youtube.com/watch?v=RTlzQEA-4oc'])
    ydl.download(['https://www.youtube.com/watch?v=zOvsyamoEDg'])
    ydl.download(['https://www.youtube.com/watch?v=ETQ4QxYNM8k'])
    ydl.download(['https://www.youtube.com/watch?v=DGrPaVZH4mE'])
    ydl.download(['https://www.youtube.com/watch?v=cbTXqKBIQ40'])
    ydl.download(['https://www.youtube.com/watch?v=bLKrNq5VMiQ'])
    ydl.download(['https://www.youtube.com/watch?v=zptCf66xGDg'])
    ydl.download(['https://www.youtube.com/watch?v=2-lFjhdlsqc'])
    ydl.download(['https://www.youtube.com/watch?v=hilPSLUFK2Q'])
    ydl.download(['https://www.youtube.com/watch?v=1Hl0Y00a44M'])
    ydl.download(['https://www.youtube.com/watch?v=riH-Nd5VbrQ'])
    ydl.download(['https://www.youtube.com/watch?v=sstcOguIloI'])
    ydl.download(['https://www.youtube.com/watch?v=kms3CKdcVWM'])
    ydl.download(['https://www.youtube.com/watch?v=xqFpnTvucTU'])
    ydl.download(['https://www.youtube.com/watch?v=iA45Om6taqg'])
    ydl.download(['https://www.youtube.com/watch?v=qdtLCfEcPL4'])
    ydl.download(['https://www.youtube.com/watch?v=qttGJ3il62Y'])
    ydl.download(['https://www.youtube.com/watch?v=UJpyFMXtZb4'])
    ydl.download(['https://www.youtube.com/watch?v=n1aSGRd0hg0'])
    ydl.download(['https://www.youtube.com/watch?v=icUC32-0WuY'])
    ydl.download(['https://www.youtube.com/watch?v=vIOSucOj2_k'])
    ydl.download(['https://www.youtube.com/watch?v=qyo_1QiYbJQ'])
    ydl.download(['https://www.youtube.com/watch?v=5gVLnu28KG4'])
    ydl.download(['https://www.youtube.com/watch?v=hrp_72heXLs'])
    ydl.download(['https://www.youtube.com/watch?v=M3yHJ4a49oc'])
    ydl.download(['https://www.youtube.com/watch?v=La4Dcd1aUcE'])
    ydl.download(['https://www.youtube.com/watch?v=qpqUKOM24Q0'])
    ydl.download(['https://www.youtube.com/watch?v=9hkY2Kqlu9U'])
    ydl.download(['https://www.youtube.com/watch?v=lS4wTuvR7Ik'])
    ydl.download(['https://www.youtube.com/watch?v=NRbD3ggyc7U'])
    ydl.download(['https://www.youtube.com/watch?v=RVTvrzjQAGY'])
    ydl.download(['https://www.youtube.com/watch?v=lODDt7q3q_M'])
    ydl.download(['https://www.youtube.com/watch?v=6qJcRQL-PqY'])
    ydl.download(['https://www.youtube.com/watch?v=O5DNxRG2-ow'])
    ydl.download(['https://www.youtube.com/watch?v=zNYDtgoKaow'])
    ydl.download(['https://www.youtube.com/watch?v=izHB2EdMngg'])
    ydl.download(['https://www.youtube.com/watch?v=0-P_YkS0z8s'])
    ydl.download(['https://www.youtube.com/watch?v=uC08L4xxjNM'])
